### PR TITLE
Created a new logo

### PR DESCRIPTION
**Pull request by Sweta271097**
Issue Number: #10 

Changes made:

Created a new logo for what-slot in such a manner that the w has a question mark embedded in it and the s shows a clock which properly showcases the essence of the name "what" and "slot" mean which timing.

logowhatslotkwoc

### CODE REVIEW

**Comment by Sweta271097** [comment]
@arnav-t Yes, absolutely.

**Comment by Sweta271097** [comment]
lws
Will this work? Should I make a PR?

**Comment by Sweta271097** [comment]
lws
Will this work? Should I make a PR?

**Comment by arnav-t** [comment]
@Sweta271097 Yeah, it works.

**Comment by Sweta271097** [comment]
@arnav-t  Made a New PR, do check.

**Comment by arnav-t** [comment]
Merged #27 
Closing this.

**Pull request closed without merging**
