### PR TITLE
Redesign Front-end

### PR DESCRIPTION
**Pull request by arc9693**
#### Screen shot for references
screenshot from 2018-12-06 20-38-20
<br>
screenshot from 2018-12-06 20-35-24
<br>

Not closing the issue here as these are some of the CSS improvements. There is scope for a lot more design improvements.Most importantly making the site responsive.

### CODE REVIEW

**Comment by arc9693** [comment]
@arnav-t Kindly review.

**Comment by arnav-t** [comment]
@arc9693 I've left a review.
Also, if you are here from KWoC, please join this [GItter channel](https://gitter.im/WhatSlotChat/Lobby).
We can further discuss the design there.

**Comment by arc9693** [comment]
Response to suggestions:
<ul>
<li> Would really like to keep the title as it is. If change is strictly needed , then OK </li>
<li> Title size correction - OK </li>
<li> Readable font for subheadings - OK </li>
<li> Sidebar looks highlighted with black color also it differentiates the sidebar section as well. Would like you to be more specific regarding changes. </li>
<li> Gradient  for the highlighted subjects - OK </li>
<li> Will change the font for uploaded file names </li>
</ul>

**Comment by arc9693** [comment]
Response to suggestions:
<ul>
<li> Would really like to keep the title as it is. If change is strictly needed , then OK </li>
<li> Title size correction - OK </li>
<li> Readable font for subheadings - OK </li>
<li> Sidebar looks highlighted with black color also it differentiates the sidebar section as well. Would like you to be more specific regarding changes. </li>
<li> Gradient  for the highlighted subjects - OK </li>
<li> Will change the font for uploaded file names </li>
</ul>

**Comment by arc9693** [comment]
Response to suggestions:
<ul>
<li> Would really like to keep the title as it is. If change is strictly needed , then OK </li>
<li> Title size correction - OK </li>
<li> Readable font for subheadings - OK </li>
<li> Sidebar looks highlighted with black color also it differentiates the sidebar section as well. Would like you to be more specific regarding changes. </li>
<li> Gradient  for the highlighted subjects - OK </li>
<li> Will change the font for uploaded file names </li>
</ul>

**Comment by arc9693** [comment]
screenshot from 2018-12-14 00-34-16

@arnav-t 
Hope we are good to go now! Kindly review. :smile:

**Pull request merged**
